# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Himanshu's Blog
email: himanshukattelu (at) gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write about things that I find interesting,
  things that are going on in my life, and things that I feel are
  worth sharing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Hkattelu.github.io/blog" # the base hostname & protocol for your site
twitter_username: Hkattelu
github_username:  Hkattelu

# Build settings
markdown: kramdown
