# Site settings
title: Himanshu's Blog
email: himanshukattelu (at) gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I try to figure out things that don't make sense.
  Also I write about stuff that I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Hkattelu.com" # the base hostname & protocol for your site
github_username: Hkattelu
 # Build settings
markdown: kramdown